package jm.task.core.jdbc.dao;

import jm.task.core.jdbc.model.User;
import jm.task.core.jdbc.util.Util;
import org.hibernate.Session;
import org.hibernate.Transaction;

import java.util.ArrayList;
import java.util.List;

public class UserDaoHibernateImpl implements UserDao {
    public UserDaoHibernateImpl() {

    }


    @Override
    public void createUsersTable() {

        String sql = "CREATE TABLE IF NOT EXISTS users(id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY," +
                " name VARCHAR(50), lastname VARCHAR(50),age SMALLINT)";

        try (Session session = Util.getSessionFactory().openSession()){
            Transaction transaction = session.beginTransaction();
            session.createNativeQuery(sql).executeUpdate();
            transaction.commit();

        }
        catch (Exception e){
            e.printStackTrace();
        }

    }

    @Override
    public void dropUsersTable() {

        String sql = "DROP TABLE IF EXISTS users";

        try(Session session = Util.getSessionFactory().openSession())

        {
            Transaction tr = session.beginTransaction();
            session.createNativeQuery(sql).executeUpdate();
            tr.commit();
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    @Override
    public void saveUser(String name, String lastName, byte age) {

        try(Session session = Util.getSessionFactory().openSession()) {
            Transaction transaction = session.beginTransaction();

            User user = new User(name, lastName,age);

            session.persist(user);

            transaction.commit();

            System.out.println("User с именем " + name + " добавлен в базу данных");

        }

        catch (Exception e) {
            e.printStackTrace();
        }


    }

    @Override
    public void removeUserById(long id) {

        try(Session session = Util.getSessionFactory().openSession()) {

            Transaction transaction = session.beginTransaction();

            User user = session.get(User.class,id);
            if(user != null) {
                session.remove(user);

            }
        transaction.commit();

        }
           catch (Exception e){
            e.printStackTrace();
           }

    }

    @Override
    public List<User> getAllUsers() {
        try (Session session = Util.getSessionFactory().openSession()) {
            return session.createQuery("FROM User", User.class).list();
        }catch (Exception e) {
            e.printStackTrace();
            return new ArrayList<>();
        }

    }

    @Override
    public void cleanUsersTable() {

            try (Session session = Util.getSessionFactory().openSession()) {
                Transaction tx = session.beginTransaction();


                session.createMutationQuery("DELETE FROM User").executeUpdate();

                tx.commit();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }

    }